# Generated by Django 5.1.3 on 2024-11-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_remove_perfil_usuario_perfil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
